sonar.projectKey=actividad-final-microservicios
sonar.projectName=Actividad Final Microservicios
sonar.projectVersion=1.0.0

sonar.sources=pokemon-service/src,naruto-service/src/main/java,dragonball-service/app.py,dragonball-service/swagger_config.py
sonar.tests=pokemon-service/test,naruto-service/src/test/java,dragonball-service/tests
sonar.exclusions=**/node_modules/**,**/target/**,**/__pycache__/**,**/.pytest_cache/**,**/coverage/**

sonar.javascript.lcov.reportPaths=pokemon-service/coverage/lcov.info
sonar.python.coverage.reportPaths=dragonball-service/coverage.xml
sonar.java.binaries=naruto-service/target/classes
sonar.sourceEncoding=UTF-8

# Ejecutar desde la raiz:
# sonar-scanner -Dsonar.host.url=http://localhost:9000 -Dsonar.token=TU_TOKEN
